# Import

In [ ]:
import numpy as np

In [ ]:
km = np.loadtxt('carros-km.txt')

In [ ]:
km

In [ ]:
ano = np.loadtxt('carros-anos.txt', dtype = int)

In [ ]:
ano

# KM média

In [ ]:
km_media = km / (2021 - ano)

In [ ]:
km_media

In [ ]:
2 ** 3 * 4

32

# NUMPY

In [1]:
import numpy as np

In [2]:
km = np.array([1000, 2500, 3900, 5000])

In [3]:
km

array([1000, 2500, 3900, 5000])

In [6]:
km = np.loadtxt(fname = 'carros-km.txt', dtype = int)

In [7]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [8]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [9]:
Acessorios = np.array(dados)

In [10]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

# Operações entre arrays

In [12]:
km = np.array([4000.0, 5895., 1357., 78500., 0.])
anos = np.array([2017, 2000, 2010, 2009, 2006])

In [24]:
idade = 2021 - anos

In [25]:
idade

array([ 4, 21, 11, 12, 15])

In [26]:
km_media = km / idade

In [27]:
km_media

array([1000.        ,  280.71428571,  123.36363636, 6541.66666667,
          0.        ])

In [28]:
dados = np.array([km, anos])

In [29]:
dados

array([[ 4000.,  5895.,  1357., 78500.,     0.],
       [ 2017.,  2000.,  2010.,  2009.,  2006.]])

In [30]:
dados[0]

array([ 4000.,  5895.,  1357., 78500.,     0.])

In [31]:
dados [1]

array([2017., 2000., 2010., 2009., 2006.])

In [32]:
km_media = dados[0] / (2021 - dados [1])

In [33]:
km_media

array([1000.        ,  280.71428571,  123.36363636, 6541.66666667,
          0.        ])

# Seleções com arrays

In [34]:
contador = np.arange(10)

In [35]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
item = 6
index = item - 1
contador[index]

5

# Operações com fatiamento

In [38]:
dados

array([[ 4000.,  5895.,  1357., 78500.,     0.],
       [ 2017.,  2000.,  2010.,  2009.,  2006.]])

In [39]:
dados [:, 1:4]

array([[ 5895.,  1357., 78500.],
       [ 2000.,  2010.,  2009.]])

In [40]:
dados [:, 1:4][0] / (2021 - dados [:, 1:4][1])

array([ 280.71428571,  123.36363636, 6541.66666667])

In [53]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
contador [contador > 4]

array([5, 6, 7, 8, 9])

In [55]:
dados

array([[ 4000.,  5895.,  1357., 78500.,     0.],
       [ 2017.,  2000.,  2010.,  2009.,  2006.]])

In [56]:
dados [:, dados [1] > 2000]

array([[ 4000.,  1357., 78500.,     0.],
       [ 2017.,  2010.,  2009.,  2006.]])

# Atributos e metódos com arrays

In [79]:
km = [4000, 5895, 1357, 78500, 3500]
anos = [2017, 2000, 2010, 2009, 2006]
km

[4000, 5895, 1357, 78500, 3500]

In [80]:
anos

[2017, 2000, 2010, 2009, 2006]

In [81]:
info_carros = km + anos
info_carros

[4000, 5895, 1357, 78500, 3500, 2017, 2000, 2010, 2009, 2006]

In [82]:
np.array(info_carros).reshape((5, 2), order = 'F')

array([[ 4000,  2017],
       [ 5895,  2000],
       [ 1357,  2010],
       [78500,  2009],
       [ 3500,  2006]])

In [83]:
dados_new = dados.copy()
dados_new

array([[ 4000.,  5895.,  1357., 78500.,     0.],
       [ 2017.,  2000.,  2010.,  2009.,  2006.]])

In [85]:
dados_new.resize ((3, 5), refcheck = False)

In [86]:
dados_new

array([[ 4000.,  5895.,  1357., 78500.,     0.],
       [ 2017.,  2000.,  2010.,  2009.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [87]:
dados_new [2] = dados_new [0] / (2021 - dados_new [1])

In [88]:
dados_new

array([[ 4000.        ,  5895.        ,  1357.        , 78500.        ,
            0.        ],
       [ 2017.        ,  2000.        ,  2010.        ,  2009.        ,
         2006.        ],
       [ 1000.        ,   280.71428571,   123.36363636,  6541.66666667,
            0.        ]])

# Estatistica

In [89]:
anos = np.loadtxt(fname = 'carros-anos.txt', dtype = int)
km = np.loadtxt(fname = 'carros-km.txt')
valor = np.loadtxt(fname = 'carros-valor.txt')

In [90]:
dataset = np.column_stack((anos, km, valor))

In [91]:
dataset.shape

(258, 3)

In [94]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [95]:
np.mean(dataset[:, 2])

98960.51310077519

In [96]:
np.std(dataset[:, 2])

29754.101150388564

In [97]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [99]:
dataset[:, 1].sum()

11480849.0